### ISSUE TITLE
Work items from telco

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/raster#10]
- raster:bands separate from eo:bands
- composite go into virtual assets extension into separate extension [Emmanuel]
- make band_expressions more pluggable (e.g. openeo process graph) [Matthias] -> see #9 
- potential fields from other extensions in raster band object - do it later once raster is more mature
  - sar:polarization
  - gsd
  - proj extension?
- No fields like nodata in assets, all in raster:bands
- stats uses collection stats objects from summaries. [Emmanuel] -> may be schema object later, see also https://github.com/radiantearth/stac-spec/issues/1045
  - Give potential additional fields like mean, stdev, valid_percent
- file extension: [Emmanuel to add to raster, Matt to remove from file]
  - file:bits_per_sample -> raster:bands.bits_per_sample (nbits)
  - file:data_type -> raster:bands.data_type
  - file:nodata -> raster:bands.nodata
  - file:unit -> raster:bands.unit (+ potentially a list of units that are not )
  - file:values -> new classification extension. could also apply to label ext? [Matthias] - clarify how to use with bitmasks (flag?) -> see new repo https://github.com/stac-extensions/classification
- remove overview_max_gsd and color_interpretation for now [Emmanuel]
- raster:values to be merged with composites [Emmanuel]
  - remove “from”
  - move offset, scale and unit to bands object

**Comment by emmanuelmathot** [comment]
Virtual assets draft extension is ready at https://github.com/stac-extensions/virtual-assets. Specifying it, I figured out that this new extension could apply to much more than raster composite. Therefore, I preferred keeping virtual:assrts quite generic with the core function to specify assets composition and positioning. Then, in this raster extensions, The composition part uses the `virtual-assets` and the `processing` extension. Let's discuss further to decide if we make another "meta" extension for composition.
