### ISSUE TITLE
Add raster:spatial_resolution

### ISSUE THREAD

**Issue by cholmes** [stac-extensions/raster#12]
As discussed in https://github.com/stac-utils/stactools/issues/87 there is a desire to add a field for spatial resolution to the raster extension. This is for use cases like the one described in that issue, where imagery has been processed to different resolutions. See the issue there for more discussion.

**Comment by emmanuelmathot** [comment]
Added in commit https://github.com/stac-extensions/raster/commit/ea7297d5869f6a5d7252cf188e12547ddb71ba69
