### ISSUE TITLE
stats object instead of flat stats attributes?

### ISSUE THREAD

**Issue by cholmes** [stac-extensions/raster#2]
@m-mohr brought this up on gitter:

> I'm wondering whether there's a better way to do the stats? An object would group it a bit better and could allow additional stats to be identified a bit easier.

I'm the one who pushes the 'flat' thing the most, but for me that's all about searchability and displaying properly in geojson readers, as they mostly read properties 'flat' and don't handle nesting. I'm cool with it for fields like this that are just at the asset level (which most geojson readers will ignore) and/or are provided for tools more than people (who is going to read the stats_max in json and think 'oh, that's interesting'?). 

And there does seem to be some benefit for helping to group it. So I think I'm +1 on the object.

**Comment by emmanuelmathot** [comment]
I actually am more favorable for a `stats` object.  IMO, we need to clarify first the "band" object concept. If `bands` would become a "core" object, then I see more a proper statistics extension with specific fields for `bands`

**Comment by emmanuelmathot** [comment]
Discussed in meetup and transferred in #10.
