### ISSUE TITLE
Description for raster:bands?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/raster#21]
Should there be a description field for raster:bands so that people can get a feeling about what is inside the band? Not everyone can use eo:bands for name and description...

**Comment by matthewhanson** [comment]
Seems like a good addition, possibly title as well.

Also, see #22

**Comment by m-mohr** [comment]
The general metadata band-level metadata (name, title, description) should probably be unified between eo:bands and raster:bands (or be unified in a single bands array long-term, that contains raster: and eo: properties in the objects).

**Comment by matthewhanson** [comment]
Handled by https://github.com/radiantearth/stac-spec/pull/1254

Closing...
