### ISSUE TITLE
Raster dimensions

### ISSUE THREAD

**Issue by lveci** [stac-extensions/raster#23]
It would be really useful to have **raster_width** and **raster_height** to know the dimensions without having to open the asset.

**Comment by matthewhanson** [comment]
Hi @lveci ,

The projection extension already has a field with the shape of the array, along with projection info and the geotransform:
https://github.com/stac-extensions/projection

So it's recommended to use that (along with raster) so no need to duplicate that info here.

Also note that the projection extension is used by downstream libraries such as https://github.com/gjoseph92/stackstac.
There's also a GDAL driver for STAC Items that will require it:
https://github.com/OSGeo/gdal/pull/4138

**Comment by lveci** [comment]
ok gotcha. The raster extension also overlaps EO making it a little confusing
