### ISSUE TITLE
Relationship clarity with eo:bands?

### ISSUE THREAD

**Issue by cholmes** [stac-extensions/raster#3]
From gitter.

@m-mohr:
> It sometimes not clear whether the bands refer to eo:bands or raster:bands. I guess it's always raster bands, but some clarifications would probably help. Is there any relation to eo:bands at all?

@matthewhanson:
> Regarding “bands”….I agree with @m-mohr about the confusion, but sorta like raster:bands here better than in EO. Here it’s a more of a general construct where you can put multiple fields for each band, whereas eo:bands is just for spectral info.
Having both eo:bands and raster:bands is definitely confusing though. I’d want to put my band info in raster:bands

**Comment by cholmes** [comment]
And my thoughts:

Uhhh... Do we need to remove eo from being a core extension? I think I agree with Matt - these feel like better 'bands' objects, that work with any raster data. And then it seems like the eo extension should provide 'common_name', 'center_wavelength', and 'full_width_half_max' as fields to add on top of the core band construct. And move 'description' and 'name' to be in the generic band object.

I definitely don't think we can propose replacing eo:bands at this late stage. But I think if we move it out of core spec then it's easier to just evolve the two in their own releases...

**Comment by matthewhanson** [comment]
I like the idea of a general "bands" object that allows you to specify any asset fields as a list of objects corresponding to bands/datasets in the file.

This way we only need to define new asset fields, but need not specify they are part of this bands object. Any asset defined fields are assumed to apply to all bands in the file.

The nice thing with this is that we aren't limited to fields defined in this extension, but other fields from core or other extensions could be here. 

For instance:

```
bands: [{
   "title": "red",
   "stats:min": 0,
   "gsd": 10.0
}]
```

**Comment by matthewhanson** [comment]
@cholmes I'm thinking the exact same thing.   You can define the spectral band information just at the asset level which is useful for single band files. In the case if multi-band files you have an array of objects.

Clearly there are many fields that wouldn't make sense to specify at the band level, but leaving it open is really flexible. I like it.

**Comment by emmanuelmathot** [comment]
I have the feeling to have "throw a paving stone in the pond" as we say in good french... ;-)
Anyway, is there a proper way to proceed with a kind of "band" core object in assets at this late stage of 1.0.0 release? Maybe later for a major update?

**Comment by m-mohr** [comment]
I feel like we are mixing things up here. There is a difference between spectral bands and what a "layer" in a raster file is.

EO defines spectral bands and due to the lack of a "layer" descriptor, we made it somehow work that it also fulfills that role. For example, many people now do actually provide QA layers as spectral bands, but that's clearly wrong. I think the right (backward-compatible) way would be something like this:
```
{
	"assets":
		"data": {
			"href": "merged_product.tif",
			"eo:bands": [
				{
					"name": "B1",
					"common_name": "coastal",
					"center_wavelength": 4.439
				},
				{ ... },
				{
					"name": "B12",
					"common_name": "swir22",
					"center_wavelength": 2.2024
				}
			],
			"raster:layers": [
				{
					"name": "B1"
				},
				{ ... },
				{
					"name": "B12"
				},
				{
					"name": "cloud_mask",
					"description": "Cloud mask for MSI"
				},
				{
					"name": "QA",
					"description": "QA info from S2"
				},
				{
					"name": "SAR-VV",
					"sar:polarizations": [
						"VV"
					]
				}
			]
		}
	}
}
```

Long term (i.e. after 1.0), eo:bands should be stricter and require spectral information, e.g. the wavelength. if there's no wavelength it's not a spectral band. We could also think about somehow better merge these, but short-term we are in RC and should not do any breaking changes to not loose trust.

**Comment by emmanuelmathot** [comment]
layer terminology is more applicable to vector data. Band is the right term for raster. (see gdal)

**Comment by m-mohr** [comment]
I was just coming from raster image terminology as you find it in any raster graphic program, e.g. Photoshop. AFAIK in most graphic programs its layers.

**Comment by emmanuelmathot** [comment]
I understand the usage in graphics software because you pile up layers with different element to form the same image (vertical). With bands in raster, the idea is more to have different values of the same pixel that you combine or not (horizontal). Then for SAR, we always use band term to select the polarization (or swath) that is the counterpart of the spectral band in optical

**Comment by m-mohr** [comment]
I don't really care what name it has as long as it is very clear and doesn't confuse users wrt to eo:bands.
Having that said, my main point above is not related to the name but to the separation of concerns (spectral bands vs. bands/layers in a file).

**Comment by cholmes** [comment]
I think I agree that's the right backwards-compatible way to do it. But if we did have a blank slate it does feel like 'bands' should not be 'eo', it should be more general, and 'eo' would just provide its values. So then you'd just have one bands array, instead of two. Would you agree with that @m-mohr? Like I don't see a strong argument that there is a fundamental separation of concerns between spectral bands and bands/layers in a file, particularly at the asset level. There is the fundamental concept of bands, and some of those are spectral.

If we were post 1.0 I agree the backwards-compatible way would be our only option.

Since we're so close to 1.0 I don't think we could just replace eo:bands with raster:bands. But I do think our one option is to take eo out of core. Then we can offer both the backwards compatible way (two band arrays), but could also just specify the eo band fields and let people choose to adopt the new raster:bands and just use the eo: fields in it.

**Comment by m-mohr** [comment]
I neither fully agree nor fully disagree. It depends on what the meaning behind the (order of the) array we would like to have and it's going a bit back also to the discussion about eo:bands in properties and/or arrays. Searching for spectral details (e.g. wavelength between x and y) could be important and then you'd like to have eo:bands as array in item properties while in assets it's more a descriptive thing to describe how the file is structured. If we'd completely start fully from scratch, I'd likely take a completely different approach:

```
{
	"properties": {
		"optical:bands": {
			"B1": {
				"common_name": "coastal",
				"center_wavelength": 4.439
			},
			{ ... },
			"B12": {
				"common_name": "swir22",
				"center_wavelength": 2.2024
			}
		}
	},
	"assets":
		"data": {
			"href": "merged_product.tif",
			"file:layers": [
				{
					"name": "band_01",
					"type": "raster",
					"optical:band": "B1",
					"raster:data_type": "float"
				},
				{ ... },
				{
					"optical:band": "B12",
					"raster:data_type": "float"
				},
				{
					"name": "cloud_mask",
					"description": "Cloud mask for MSI",
					"raster:values": [...]
				},
				{
					"name": "QA",
					"description": "QA info from S2"
				},
				{
					"name": "SAR-VV",
					"sar:polarization": "VV"
				},
				{
					"name": "boundary",
					"type": "vector"
				}
			]
		}
	}
}
```
Or something similar, that would be a whole new discussion.

Again, I'd NOT change anything wrt to eo:bands anymore. We are in RC, any breaking change should be avoided that includes eo. We have released it as part of rc1 and thus it's part of the contract, no matter it's a core extension or not.

**Comment by emmanuelmathot** [comment]
As a more general thought (maybe naive): what is the basic problem of using the same field name since at the end, they are clearly defined in 2 different namespaces clearly identified by prefixes that should avoid confusion. If they both converged in their semantics, a merge into a more basic core object in a future release is still an option.

**Comment by matthewhanson** [comment]
I think the name "bands" is ok, and I can't think of a better name for the concept here.

I think I would like to see the bands field without a prefix and in it's own extension that could eventually be moved into core.  

Then, all other properties wouldn't be part of the bands object but instead just defined at the asset level. Only in the case of multiple bands per file would you need to use the bands field.

**Comment by emmanuelmathot** [comment]
Discussed in meetup and transferred in #10.
