### ISSUE TITLE
schema description doesn't match what the text says for unit/scale/offset

### ISSUE THREAD

**Issue by philvarner** [stac-extensions/raster#32]
The schema says that:
- `unit` is "Unit denomination of the pixel value"
- `scale` is "multiplicator factor of the pixel value to transform into the value
- `offset` is "number to be added to the pixel value to transform into the value"

note the specific use of "pixel value" rather than "the value"

However, the example in the README of how to transform a unitless DN to Radiance seems to specify the unit *after* the conversion:
 ```
 "unit": "W⋅sr−1⋅m−3",
 "scale": 0.0145,
 "offset": 3.48
 ```

**Comment by emmanuelmathot** [comment]
maybe the "pixel" word is superfluous.
Concerning the scale and offset, those are parameters of a function for the data value to get the proper value in the specified unit. Initially, it was proposed to have an array of objects to specify several values (e.g. radiance, TOA reflectance, BOA, ...)
Maybe a clarification may help in the readme.

**Comment by arthurelmes** [comment]
Also, shouldn't the radiance units be watts * sr-1 * m^2 instead of m^3?
