### ISSUE TITLE
Allow or forbid in Item properties?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/raster#36]
Right now raster:bands is forbidden in Item properties (or at least undefined) and as such it is not validated, which may lead to issues:
https://github.com/microsoft/PlanetaryComputerDataCatalog/issues/383

**Comment by emmanuelmathot** [comment]
I remember a discussion about making sure that a band is always linked to an asset. Then if a change is necessary in the schema to forbid it at item level, then I can add it.

**Comment by emmanuelmathot** [comment]
In a consistent view of the [RFC for bands](https://github.com/radiantearth/stac-spec/pull/1254), we should forbid the raster:bands at item level

**Comment by m-mohr** [comment]
Obsolete with the Bands RFC!
