### ISSUE TITLE
Field to describe the amount of data pixels

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/raster#39]
In raster imagery you often have these "blackfilled" parts around the scene. Not sure how these are called correctly, but it would be useful to specify a field that describes how many pixels are actual data values (incl. clouds etc.), either as percentage (or as number of pixels?). This would help to filter assets that just have tiny bits of actually usable information.

I think this should be a field per raster image, not per band, right?

Planet is calling such a field black_fill ("The percentage of the item containing black fill (0-100)").

cc @cholmes 

Thoughts? Ideas for names?

Edit:
- Planet: black_fill
- Sentinel: blind_pixels
- Landsat: n/a?

**Comment by m-mohr** [comment]
Meeting: Seems like a good idea, just needs a good description and name. Maybe "valid_..." or so.

**Comment by emmanuelmathot** [comment]
With Sentinel-2, we often use the term `blind pixels`

**Comment by m-mohr** [comment]
Thinking about it "fill" is really a good term because the image really just is filled with something to make it rectangular. It looks like in general imagery there's no term for it, at least I haven't found it yet. It's not necessarily black so that should not be included. So if we want to describe it, it could be something like "outside_coverage_fill" or so.

**Comment by emmanuelmathot** [comment]
Isn't `valid_percent` field in [statistics](https://github.com/stac-extensions/raster#statistics-object) object already representing that value?

**Comment by m-mohr** [comment]
If there's no further demand apart from Planet we can close it for now. please chime in if you have a usecase for it.
