### ISSUE TITLE
infinity, NaN in band statistics

### ISSUE THREAD

**Issue by bossie** [stac-extensions/raster#40]
So we've run into this case where GDAL reports e.g. a maximum of Infinity and a mean of NaN for a raster.

Should the [specification for the Statistics Object](https://github.com/stac-extensions/raster#statistics-object) not be updated to allow these special values like `nodata` does?

**Comment by m-mohr** [comment]
STAC sprint (subgroup):

For statistics, I think we should clarify that basically -infinity is the default for minimum and +infinity is the default for maximum. 
nan for statistics doesn't make a lot of sense to me. Why not just omit the property then?
Having strings in the statistics seems like a bad idea to us.

**Comment by m-mohr** [comment]
Is now present as part of the Bands RFC.
