### ISSUE TITLE
Array for spatial_resolution?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/raster#46]
I see it in several "unofficial" fields, that spatial resolution is provided as an array of two numbers.
Could we say that spatial_resolution additionally could also be an array of two numbers, similar to proj:shape?

**Comment by emmanuelmathot** [comment]
like a min/max ?

**Comment by vincentsarago** [comment]
Usually it's the resolution in `X` and `Y` axes I think

**Comment by vincentsarago** [comment]
I think this was discussed earlier, but having just a number or an array of number does not mean a lot without a CRS component and a Lat/Lon, which is why the `projection` extension should be used for this! I'm not quite sure of the usage of this field within this extension to be honest

**Comment by emmanuelmathot** [comment]
Indeed this the raster extension... I initially got confused with sat swath resolution.
I tend to agree with @vincentsarago about the meaning without a CRS.
This extension should only describe the pixel values properties in the raster. With time, I realize `spatial_resolution` should not be there. This gives an ambiguous information about the resolution (ground?, data acquisition?, CRS?, [instrument](https://github.com/radiantearth/stac-spec/issues/1196))
Maybe we should deprecate it and give instead a best practice on how to get properly the raster size wrt the CRS
```python
src = gdal.Open(raster)
xres = src.RasterXSize
yres = src.RasterYSize
```

**Comment by m-mohr** [comment]
Makes sense. Where should this live ideally? In proj? It's not ideal that people come up with fields such as `s3:spatial_resolution` etc.

**Comment by vincentsarago** [comment]
it's already in the `projection` extension as part of the `proj:transform` https://github.com/stac-extensions/projection?tab=readme-ov-file#projtransform

**Comment by m-mohr** [comment]
Hmm, seems that's not what people are looking for and is - for the average user - probably also too difficult to understand?!
