### ISSUE TITLE
Best practices for `unit` values?

### ISSUE THREAD

**Issue by tylere** [stac-extensions/raster#47]
The current raster spec does not give much guidance about the `unit` field, and inconsistency in the field may make datasets less interoperable.

As a concrete example, should a unit be `meter` or `metre` or `meters` or `m` or `cm` or `km`?

It would be good to describe a best practice for this field. For example:
- Use the [International System of Units (SI)](https://www.bipm.org/en/measurement-units) Here is a good [overview](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-concise-EN.pdf/2fda4656-e236-0fcb-3867-36ca74eea4e3)
- Use [SI base units](https://www.bipm.org/en/measurement-units/si-base-units) or [SI derived units](https://www.nist.gov/pml/special-publication-330/sp-330-section-2#2.3.4)
- Use the raster extension `scale` field rather than [SI prefixes](https://www.bipm.org/en/measurement-units/si-prefixes)
- Use [unit symbols](https://www.nist.gov/pml/special-publication-330/sp-330-section-5#5.2) rather than [unit names](https://www.nist.gov/pml/special-publication-330/sp-330-section-5#5.3)

**Comment by m-mohr** [comment]
The datacube extension (and others, too, I think) use:

> The unit of measurement for the data, preferably compliant to [UDUNITS-2](https://ncics.org/portfolio/other-resources/udunits2/) units (singular).

Is this good enough? It's difficult to standardize here as people have so diverging needs.
This field will be migrated to STAC core metadata in 1.1 (raster 2.0) so is not that relevant for the raster extension, but for core.

**Comment by m-mohr** [comment]
Implemented in https://github.com/radiantearth/stac-spec/pull/1254 through commit https://github.com/radiantearth/stac-spec/pull/1254/commits/f35f5d8cf63f1f12ea1da59cd21825f32a08898c
