### ISSUE TITLE
Use Expression Object for band_expression

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/raster#9]
From recent discussion:

> make band_expressions more pluggable (e.g. openeo process graph) [Matthias]
> - maybe put them in “virtual” assets
> - make object with type (e.g. riotiler, openeo) and expression (anything)
> - new extension?

=> Instead of new extension, added to processing extension.

PR is here: https://github.com/stac-extensions/processing/pull/2

**Comment by emmanuelmathot** [comment]
transferred in https://github.com/stac-extensions/virtual-assets, where PR https://github.com/stac-extensions/processing/pull/2 is referenced in readme until resolution
